language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

before_install:
  - (echo 'no' | pecl install apcu) || true
  - cp php.ini ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - composer install
  - phpunit --coverage-clover=coverage.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="$SCRUTINIZER_TOKEN" --format=php-clover coverage.xml
